name: Scan Docker Hub Image for Vulnerabilities

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of the Docker Hub image to scan (including tag)'
        required: true
        type: string

jobs:
  scan-docker-hub-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Image from Docker Hub
        run: |
          docker pull ${{ inputs.IMAGE_NAME }}

      - name: Scan Docker Image with Anchore
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.IMAGE_NAME }}
          fail-severity: 'high'
          format: 'table'
