name: Scan Docker Hub Image for Vulnerabilities

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        description: 'The name of the Docker Hub image to scan (including tag e.g alpine:latest)'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      IMAGE_NAME: {}


jobs:
  scan-docker-hub-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Image from Docker Hub
        run: |
          docker pull ${{ inputs.IMAGE_NAME }}

      - name: Scan Docker Image with Anchore
        id: anchore-scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.IMAGE_NAME }}
          fail-build: true
          severity-cutoff: high
          output-format: json  # Change output format to JSON

      - name: Save Anchore Scan Report as JSON
        run: echo "${{ steps.anchore-scan.outputs.scan-results }}" > anchore-scan-report.json

      - name: Upload Anchore Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: anchore-scan-report
          path: anchore-scan-report.json
