# javascript: Get app variables
on:
  workflow_call:

jobs:
  get_app_variables:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.set_vars.outputs.app_name }}
      image_name: ${{ steps.set_vars.outputs.image_name }}
      version: ${{ steps.set_vars.outputs.version }}
    steps:
      - run: sudo apt-get install jq
      - id: set_vars
        run: |
          APP_NAME=$(jq -r '.app_name' ./app.config.json)
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          IMAGE_NAME=$(jq -r '.image_name' ./app.config.json)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          VERSION=$(jq -r '.version' ./package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
