name: Python Tests for Applications

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
        description: The python version to test against
      PYTEST:
        required: false
        type: boolean
        description: If set test will attempt to run pytest over unittest
        default: false
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Prepare pip
        run:  python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: mypy Static Type Checking
        run: python -m mypy

      - name: ruff Python Style Checking
        run:  python -m ruff check --output-format=github .

      - name: Unit Tests
        run: |
          if ${{ inputs.PYTEST }}; then
            pytest
          else
            python -m unittest discover --verbose
          fi
        shell: bash
        env:
          PYTEST: ${{ inputs.PYTEST }}
