name: Does GitHub release for given version and extracts release notes from CHANGELOG.md

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
        description: The version being released

jobs:
  do-release:
    name: Do Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # If a CHANGELOG file has been provided find the developer curated release notes for 
    # the release from that file
    - name: Extract Release Notes
      id: release-notes
      uses: telicent-oss/extract-release-notes-action@v1
      with:
        changelog-file: CHANGELOG.md
        version: ${{ inputs.VERSION }}
        attach-release-notes: true
        job-summary: true
        # Allow for the Change Log file to not exist, in which case we get blank release
        # notes generated
        fail-if-missing: false

    - name: Create GitHub Release
      id: create-github-release
      uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
      with:
        body_path: ${{ steps.release-notes.outputs.release-notes-file }}
        generate_release_notes: false
        name: v${{ inputs.VERSION }}
        prerelease: false
        tag_name: v${{ inputs.VERSION }}
