name: Scan Container Image with Trivy

on:
  workflow_call:
    inputs:
      GITHUB_REF:
        required: false
        type: string
        description: |
          pass in \$\{\{ github.ref \}\} to allow this workflow's "if" conditions to resemble
          triggering workflows
      SCAN_NAME:
        type: string
        description: |
          A developer friendly name for the image to diffentiate scan reports where a repository is
          building multiple images.
      IMAGE_REF:
        type: string
        description: |
          Specifies the full image reference (repository, name and tag) for an image you wish to scan.
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: ${{ inputs.IMAGE_REF }}
          output: trivy-docker-report.json
          format: json
          exit-code: 0

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-report-${{ inputs.SCAN_NAME }}
          path: trivy-docker-report.json
          retention-days: 30
      - name: Check github.ref
        run: echo "The github.ref is ${{ github.ref }}"
      - name: Release sbom
        uses: softprops/action-gh-release@v2
        if: startsWith(inputs.GITHUB_REF, 'refs/tags/')
        with:
          files: |
            trivy-docker-report.json
  
      - name: Fail Build on High/Critical Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: ${{ inputs.IMAGE_REF }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
