name: Vulnerability Scanning on Repo
on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
        description: The Name of the app being checked
        default: test
      working-directory:
        required: false
        default: .
        type: string
      #      vuln-type:
      #        required: false
      #        default: 'library'
      #        description: 'comma-separated list of vulnerability types (os,library)'

env:
  BOM_FILE_PATH: "${{ inputs.working-directory }}/${{ inputs.APP_NAME }}.sbom.json"

jobs:
  generate_bom:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        uses: martinbeentjes/npm-get-version-action@main
        id: package-version
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Get node version
        id: node
        run: |
          echo "version=$(node -v)" >> $GITHUB_OUTPUT
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
      - run: yarn install
      - name: Create sbom output with CycloneDX
        id: cyclonedx
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          path: ${{ inputs.working-directory }}
          output: ${{ env.BOM_FILE_PATH }}
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }}-sbom.json
          path: ${{ env.BOM_FILE_PATH }}
  run_low_risk_vulnerability_scanner:
    needs:
      - generate_bom
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact       
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_number }}-sbom.json
      - name: Scan SBOM
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: '0'
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM'
          ignore-unfixed: true
          input: ${{ github.run_number }}-sbom.json
          scan-type: 'sbom'
  run_high_risk_vulnerability_scanner:
    needs:
      - generate_bom
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact       
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_number }}-sbom.json
      - name: 
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: '1'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          input: ${{ github.run_number }}-sbom.json
          scan-type: 'sbom'
